package clases;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ PandicornioSoft Inc.
//  @ Licensed by Pandicornio Corporation
//  @ Project : Cartera_de_Clientes
//  @ File Name : ActividadComercial.java
//  @ Date : 23/08/2014
//  @ Author : Mauro Leonardo P�rez Bravo
//
//



public class ActividadComercial {

    public String rfc = "";
    public String giroComercial = "";
	
    public String getRFC() {
		return rfc;
    }
    
    public String getGiroComercial() {
		return giroComercial;
    }
    
    public void setRFC(String s) {
		rfc = s ;
    }
    
    public void setGiroComercial(String s) {
		giroComercial = s ;
    }
}
