package clases;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ PandicornioSoft Inc.
//  @ Licensed by Pandicornio Corporation
//  @ Project : Cartera_de_Clientes
//  @ File Name : Contacto.java
//  @ Date : 23/08/2014
//  @ Author : Mauro Leonardo P�rez Bravo
//
//



public class Contacto extends PersonaFisica {

    public String cargo = "";
	
    public String getCargo() {
		return cargo;
    }
    
    public void setCargo(String s) {
		cargo = s ;
    }
}
