package clases;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ PandicornioSoft Inc.
//  @ Licensed by Pandicornio Corporation
//  @ Project : Cartera_de_Clientes
//  @ File Name : Direccion.java
//  @ Date : 23/08/2014
//  @ Author : Mauro Leonardo P�rez Bravo
//
//
public class Direccion {

    public String calle = "";
    public String numInterior = "";
    public String numExterior = "";
    public String codigoPostal = "";
    public String ciudad = "";
    public String pais = "";
    
    public String getCalle() {
		return calle;
    }
    
    public String getNumInterior() {
		return numInterior;
    }
    
    public String getNumExterior() {
		return numExterior;
    }
    
    public String getCodigoPostal() {
		return codigoPostal;
    }
    
    public String getCiudad() {
		return ciudad;
    }
    
    public String getPais() {
		return pais;
    }
    
    public void setCalle(String s) {
		calle = s;
    }
    
    public void setNumInterior(String s) {
		numInterior = s;
    }
    
    public void setNumExterior(String s) {
		numExterior = s;
    }
    
    public void setCodigoPostal(String s) {
		codigoPostal = s;
    }
    
    public void setCiudad(String s) {
		ciudad = s;
    }
    
    public void setPais(String s) {
		pais = s;
    }
}