package clases;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ PandicornioSoft Inc.
//  @ Licensed by Pandicornio Corporation
//  @ Project : Cartera_de_Clientes
//  @ File Name : MediosDigitales.java
//  @ Date : 23/08/2014
//  @ Author : Mauro Leonardo P�rez Bravo
//
//

import java.util.*;



public class MediosDigitales {

    public ArrayList<String> correos = new ArrayList<String>();
    public ArrayList<String> tipos = new ArrayList<String>();
	
    public ArrayList<String> getCorreos() {
		return correos;
    }
    
    public void setCorreos(ArrayList<String> s) {
		correos = s ;
    }
    public ArrayList<String> getTipos() {
		return tipos;
    }
    
    public void setTipos(ArrayList<String> s) {
		tipos = s ;
    }
}