package clases;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ PandicornioSoft Inc.
//  @ Licensed by Pandicornio Corporation
//  @ Project : Cartera_de_Clientes
//  @ File Name : NombrePropio.java
//  @ Date : 23/08/2014
//  @ Author : Mauro Leonardo P�rez Bravo
//
//

public class NombrePropio {

    public String nombre = "";
    public String aPaterno = "";
    public String aMaterno = "";
	
    public String getNombre() {
		return nombre;
    }
    
    public String getPaterno() {
		return aPaterno;
    }
    
    public String getMaterno() {
		return aMaterno;
    }
    
    public void setNombre(String s) {
		nombre = s;
    }
    
    public void setPaterno(String s) {
		aPaterno = s;
    }
    
    public void setMaterno(String s) {
		aMaterno = s;
    }
}
