package clases;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ PandicornioSoft Inc.
//  @ Licensed by Pandicornio Corporation
//  @ Project : Cartera_de_Clientes
//  @ File Name : PersonaFisica.java
//  @ Date : 23/08/2014
//  @ Author : Mauro Leonardo P�rez Bravo
//
//


import java.util.*;


public class PersonaFisica {

    public NombrePropio nombre = new NombrePropio();
    public Direccion direccion = new Direccion();
    public String curp = "";
    public MediosDigitales mediosDigitales = new MediosDigitales();
    public ActividadComercial actividadComercial = new ActividadComercial();
    public ArrayList<Telefono> telefonos = new ArrayList<Telefono>();
}
