package clases;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ PandicornioSoft Inc.
//  @ Licensed by Pandicornio Corporation
//  @ Project : Cartera_de_Clientes
//  @ File Name : PersonaMoral.java
//  @ Date : 23/08/2014
//  @ Author : Mauro Leonardo P�rez Bravo
//
//

import java.util.*;


public class PersonaMoral extends PersonaFisica {

    public String razonSocial = "";
    public ArrayList<Contacto> contactos = new ArrayList<Contacto>();
    public ActividadComercial empresa = new ActividadComercial();
	
    public String getRazonSocial() {
		return razonSocial;
    }
    
    public void setRazonSocial(String s) {
		razonSocial = s ;
    }
    
    public void addContacto(String cargo, String nombre, String paterno, String materno) {
		Contacto jacinto = new Contacto();
		jacinto.setCargo(cargo);
		jacinto.nombre.setNombre(nombre);
		jacinto.nombre.setPaterno(paterno);
		jacinto.nombre.setMaterno(materno);
		
    }
    
    public void removeContacto() {
    
    }
    
    public void changeContacto() {
    
    }
    
    public void findContacto() {
    
    }
}