package clases;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ PandicornioSoft Inc.
//  @ Licensed by Pandicornio Corporation
//  @ Project : Cartera_de_Clientes
//  @ File Name : Telefono.java
//  @ Date : 23/08/2014
//  @ Author : Mauro Leonardo P�rez Bravo
//
//

import java.util.*;

public class Telefono {

    public String numero = "";
    public String ubicacion = "";
   
    public String getNumero() {
		return numero;
    }
    public String getUbicacion() {
		return ubicacion;
    }
    public void setNumero(String s) {
		numero = s;
    }	
    public void setUbicacion(String s) {
		ubicacion = s;
    }
}